spring:
  datasource:
    hikari:
      max-lifetime: 30000
      connection-test-query: SELECT 1
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://iot.cr6o4amqq5jo.ap-northeast-2.rds.amazonaws.com/iot?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&characterEncoding=UTF-8
    username: admin
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: false